// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model
import (
	"time"
)

type NewTask struct {
	Title string `json:"title" bson:"title,omitempty"`
}

type Task struct {
	ID            string    `json:"_id" bson:"_id,omitempty"`
	Title         string    `json:"title" bson:"title,omitempty" binding:"max=250"`
	Completed     bool      `json:"completed" bson:"completed,omitempty"`
	CompletedDate time.Time `json:"completed_date" bson:"completed_date,omitempty"`
	CreatedAt     time.Time `json:"created_at" bson:"created_at,omitempty"`
	UpdatedAt     time.Time `json:"updated_at" bson:"updated_at,omitempty"`
	UserID        string    `json:"user_id" bson:"user_id,omitempty"`
}

type UpdateTask struct {
	ID        string `json:"_id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}
